# Generated by Django 4.2.1 on 2023-05-07 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^[a-zA-Z0-9]+$"),
                            django.core.validators.MinLengthValidator(6),
                        ],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^[ -~]+$"),
                            django.core.validators.MinLengthValidator(8),
                        ],
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("comment", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
